/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedCreditsRouteImport } from './routes/_authenticated.credits'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedNewProjectRouteImport } from './routes/_authenticated.new-project'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated.projects.$projectId'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated.projects.$projectId.index'
import { Route as AuthenticatedProjectsProjectIdBudgetRouteImport } from './routes/_authenticated.projects.$projectId.budget'
import { Route as AuthenticatedProjectsProjectIdBuildRouteImport } from './routes/_authenticated.projects.$projectId.build'
import { Route as AuthenticatedProjectsProjectIdDocumentsRouteImport } from './routes/_authenticated.projects.$projectId.documents'
import { Route as AuthenticatedProjectsProjectIdExperimentsRouteImport } from './routes/_authenticated.projects.$projectId.experiments'
import { Route as AuthenticatedProjectsProjectIdMentorRouteImport } from './routes/_authenticated.projects.$projectId.mentor'
import { Route as AuthenticatedProjectsProjectIdRequirementsRouteImport } from './routes/_authenticated.projects.$projectId.requirements'
import { Route as AuthenticatedProjectsProjectIdResearchRouteImport } from './routes/_authenticated.projects.$projectId.research'
import { Route as AuthenticatedProjectsProjectIdReviewRouteImport } from './routes/_authenticated.projects.$projectId.review'
import { Route as AuthenticatedProjectsProjectIdRisksRouteImport } from './routes/_authenticated.projects.$projectId.risks'
import { Route as AuthenticatedProjectsProjectIdScheduleRouteImport } from './routes/_authenticated.projects.$projectId.schedule'
import { Route as AuthenticatedProjectsProjectIdShowcaseRouteImport } from './routes/_authenticated.projects.$projectId.showcase'
import { Route as AuthenticatedProjectsProjectIdStakeholdersRouteImport } from './routes/_authenticated.projects.$projectId.stakeholders'
import { Route as AuthenticatedProjectsProjectIdTasksRouteImport } from './routes/_authenticated.projects.$projectId.tasks'
import { Route as AuthenticatedProjectsProjectIdTestingRouteImport } from './routes/_authenticated.projects.$projectId.testing'
import { Route as AuthenticatedProjectsProjectIdMentorIndexRouteImport } from './routes/_authenticated.projects.$projectId.mentor.index'
import { Route as AuthenticatedProjectsProjectIdMentorThreadIdRouteImport } from './routes/_authenticated.projects.$projectId.mentor.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreditsRoute = AuthenticatedCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewProjectRoute = AuthenticatedNewProjectRouteImport.update({
  id: '/new-project',
  path: '/new-project',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdBudgetRoute =
  AuthenticatedProjectsProjectIdBudgetRouteImport.update({
    id: '/budget',
    path: '/budget',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdBuildRoute =
  AuthenticatedProjectsProjectIdBuildRouteImport.update({
    id: '/build',
    path: '/build',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdDocumentsRoute =
  AuthenticatedProjectsProjectIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdExperimentsRoute =
  AuthenticatedProjectsProjectIdExperimentsRouteImport.update({
    id: '/experiments',
    path: '/experiments',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdMentorRoute =
  AuthenticatedProjectsProjectIdMentorRouteImport.update({
    id: '/mentor',
    path: '/mentor',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdRequirementsRoute =
  AuthenticatedProjectsProjectIdRequirementsRouteImport.update({
    id: '/requirements',
    path: '/requirements',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdResearchRoute =
  AuthenticatedProjectsProjectIdResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdReviewRoute =
  AuthenticatedProjectsProjectIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdRisksRoute =
  AuthenticatedProjectsProjectIdRisksRouteImport.update({
    id: '/risks',
    path: '/risks',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdScheduleRoute =
  AuthenticatedProjectsProjectIdScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdShowcaseRoute =
  AuthenticatedProjectsProjectIdShowcaseRouteImport.update({
    id: '/showcase',
    path: '/showcase',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdStakeholdersRoute =
  AuthenticatedProjectsProjectIdStakeholdersRouteImport.update({
    id: '/stakeholders',
    path: '/stakeholders',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdTasksRoute =
  AuthenticatedProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdTestingRoute =
  AuthenticatedProjectsProjectIdTestingRouteImport.update({
    id: '/testing',
    path: '/testing',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdMentorIndexRoute =
  AuthenticatedProjectsProjectIdMentorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdMentorRoute,
  } as any)
const AuthenticatedProjectsProjectIdMentorThreadIdRoute =
  AuthenticatedProjectsProjectIdMentorThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedProjectsProjectIdMentorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new-project': typeof AuthenticatedNewProjectRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/projects/$projectId/budget': typeof AuthenticatedProjectsProjectIdBudgetRoute
  '/projects/$projectId/build': typeof AuthenticatedProjectsProjectIdBuildRoute
  '/projects/$projectId/documents': typeof AuthenticatedProjectsProjectIdDocumentsRoute
  '/projects/$projectId/experiments': typeof AuthenticatedProjectsProjectIdExperimentsRoute
  '/projects/$projectId/mentor': typeof AuthenticatedProjectsProjectIdMentorRouteWithChildren
  '/projects/$projectId/requirements': typeof AuthenticatedProjectsProjectIdRequirementsRoute
  '/projects/$projectId/research': typeof AuthenticatedProjectsProjectIdResearchRoute
  '/projects/$projectId/review': typeof AuthenticatedProjectsProjectIdReviewRoute
  '/projects/$projectId/risks': typeof AuthenticatedProjectsProjectIdRisksRoute
  '/projects/$projectId/schedule': typeof AuthenticatedProjectsProjectIdScheduleRoute
  '/projects/$projectId/showcase': typeof AuthenticatedProjectsProjectIdShowcaseRoute
  '/projects/$projectId/stakeholders': typeof AuthenticatedProjectsProjectIdStakeholdersRoute
  '/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRoute
  '/projects/$projectId/testing': typeof AuthenticatedProjectsProjectIdTestingRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/mentor/$threadId': typeof AuthenticatedProjectsProjectIdMentorThreadIdRoute
  '/projects/$projectId/mentor/': typeof AuthenticatedProjectsProjectIdMentorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new-project': typeof AuthenticatedNewProjectRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/projects/$projectId/budget': typeof AuthenticatedProjectsProjectIdBudgetRoute
  '/projects/$projectId/build': typeof AuthenticatedProjectsProjectIdBuildRoute
  '/projects/$projectId/documents': typeof AuthenticatedProjectsProjectIdDocumentsRoute
  '/projects/$projectId/experiments': typeof AuthenticatedProjectsProjectIdExperimentsRoute
  '/projects/$projectId/requirements': typeof AuthenticatedProjectsProjectIdRequirementsRoute
  '/projects/$projectId/research': typeof AuthenticatedProjectsProjectIdResearchRoute
  '/projects/$projectId/review': typeof AuthenticatedProjectsProjectIdReviewRoute
  '/projects/$projectId/risks': typeof AuthenticatedProjectsProjectIdRisksRoute
  '/projects/$projectId/schedule': typeof AuthenticatedProjectsProjectIdScheduleRoute
  '/projects/$projectId/showcase': typeof AuthenticatedProjectsProjectIdShowcaseRoute
  '/projects/$projectId/stakeholders': typeof AuthenticatedProjectsProjectIdStakeholdersRoute
  '/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRoute
  '/projects/$projectId/testing': typeof AuthenticatedProjectsProjectIdTestingRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/mentor/$threadId': typeof AuthenticatedProjectsProjectIdMentorThreadIdRoute
  '/projects/$projectId/mentor': typeof AuthenticatedProjectsProjectIdMentorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/credits': typeof AuthenticatedCreditsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/new-project': typeof AuthenticatedNewProjectRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/_authenticated/projects/$projectId/budget': typeof AuthenticatedProjectsProjectIdBudgetRoute
  '/_authenticated/projects/$projectId/build': typeof AuthenticatedProjectsProjectIdBuildRoute
  '/_authenticated/projects/$projectId/documents': typeof AuthenticatedProjectsProjectIdDocumentsRoute
  '/_authenticated/projects/$projectId/experiments': typeof AuthenticatedProjectsProjectIdExperimentsRoute
  '/_authenticated/projects/$projectId/mentor': typeof AuthenticatedProjectsProjectIdMentorRouteWithChildren
  '/_authenticated/projects/$projectId/requirements': typeof AuthenticatedProjectsProjectIdRequirementsRoute
  '/_authenticated/projects/$projectId/research': typeof AuthenticatedProjectsProjectIdResearchRoute
  '/_authenticated/projects/$projectId/review': typeof AuthenticatedProjectsProjectIdReviewRoute
  '/_authenticated/projects/$projectId/risks': typeof AuthenticatedProjectsProjectIdRisksRoute
  '/_authenticated/projects/$projectId/schedule': typeof AuthenticatedProjectsProjectIdScheduleRoute
  '/_authenticated/projects/$projectId/showcase': typeof AuthenticatedProjectsProjectIdShowcaseRoute
  '/_authenticated/projects/$projectId/stakeholders': typeof AuthenticatedProjectsProjectIdStakeholdersRoute
  '/_authenticated/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRoute
  '/_authenticated/projects/$projectId/testing': typeof AuthenticatedProjectsProjectIdTestingRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/projects/$projectId/mentor/$threadId': typeof AuthenticatedProjectsProjectIdMentorThreadIdRoute
  '/_authenticated/projects/$projectId/mentor/': typeof AuthenticatedProjectsProjectIdMentorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/credits'
    | '/dashboard'
    | '/new-project'
    | '/settings'
    | '/api/chat'
    | '/projects/$projectId'
    | '/projects/$projectId/budget'
    | '/projects/$projectId/build'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/experiments'
    | '/projects/$projectId/mentor'
    | '/projects/$projectId/requirements'
    | '/projects/$projectId/research'
    | '/projects/$projectId/review'
    | '/projects/$projectId/risks'
    | '/projects/$projectId/schedule'
    | '/projects/$projectId/showcase'
    | '/projects/$projectId/stakeholders'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/testing'
    | '/projects/$projectId/'
    | '/projects/$projectId/mentor/$threadId'
    | '/projects/$projectId/mentor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/credits'
    | '/dashboard'
    | '/new-project'
    | '/settings'
    | '/api/chat'
    | '/projects/$projectId/budget'
    | '/projects/$projectId/build'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/experiments'
    | '/projects/$projectId/requirements'
    | '/projects/$projectId/research'
    | '/projects/$projectId/review'
    | '/projects/$projectId/risks'
    | '/projects/$projectId/schedule'
    | '/projects/$projectId/showcase'
    | '/projects/$projectId/stakeholders'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/testing'
    | '/projects/$projectId'
    | '/projects/$projectId/mentor/$threadId'
    | '/projects/$projectId/mentor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/credits'
    | '/_authenticated/dashboard'
    | '/_authenticated/new-project'
    | '/_authenticated/settings'
    | '/api/chat'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/$projectId/budget'
    | '/_authenticated/projects/$projectId/build'
    | '/_authenticated/projects/$projectId/documents'
    | '/_authenticated/projects/$projectId/experiments'
    | '/_authenticated/projects/$projectId/mentor'
    | '/_authenticated/projects/$projectId/requirements'
    | '/_authenticated/projects/$projectId/research'
    | '/_authenticated/projects/$projectId/review'
    | '/_authenticated/projects/$projectId/risks'
    | '/_authenticated/projects/$projectId/schedule'
    | '/_authenticated/projects/$projectId/showcase'
    | '/_authenticated/projects/$projectId/stakeholders'
    | '/_authenticated/projects/$projectId/tasks'
    | '/_authenticated/projects/$projectId/testing'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/projects/$projectId/mentor/$threadId'
    | '/_authenticated/projects/$projectId/mentor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/credits': {
      id: '/_authenticated/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AuthenticatedCreditsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/new-project': {
      id: '/_authenticated/new-project'
      path: '/new-project'
      fullPath: '/new-project'
      preLoaderRoute: typeof AuthenticatedNewProjectRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/budget': {
      id: '/_authenticated/projects/$projectId/budget'
      path: '/budget'
      fullPath: '/projects/$projectId/budget'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdBudgetRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/build': {
      id: '/_authenticated/projects/$projectId/build'
      path: '/build'
      fullPath: '/projects/$projectId/build'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdBuildRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/documents': {
      id: '/_authenticated/projects/$projectId/documents'
      path: '/documents'
      fullPath: '/projects/$projectId/documents'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/experiments': {
      id: '/_authenticated/projects/$projectId/experiments'
      path: '/experiments'
      fullPath: '/projects/$projectId/experiments'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdExperimentsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/mentor': {
      id: '/_authenticated/projects/$projectId/mentor'
      path: '/mentor'
      fullPath: '/projects/$projectId/mentor'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMentorRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/requirements': {
      id: '/_authenticated/projects/$projectId/requirements'
      path: '/requirements'
      fullPath: '/projects/$projectId/requirements'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRequirementsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/research': {
      id: '/_authenticated/projects/$projectId/research'
      path: '/research'
      fullPath: '/projects/$projectId/research'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdResearchRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/review': {
      id: '/_authenticated/projects/$projectId/review'
      path: '/review'
      fullPath: '/projects/$projectId/review'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdReviewRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/risks': {
      id: '/_authenticated/projects/$projectId/risks'
      path: '/risks'
      fullPath: '/projects/$projectId/risks'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRisksRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/schedule': {
      id: '/_authenticated/projects/$projectId/schedule'
      path: '/schedule'
      fullPath: '/projects/$projectId/schedule'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdScheduleRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/showcase': {
      id: '/_authenticated/projects/$projectId/showcase'
      path: '/showcase'
      fullPath: '/projects/$projectId/showcase'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdShowcaseRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/stakeholders': {
      id: '/_authenticated/projects/$projectId/stakeholders'
      path: '/stakeholders'
      fullPath: '/projects/$projectId/stakeholders'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdStakeholdersRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/tasks': {
      id: '/_authenticated/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTasksRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/testing': {
      id: '/_authenticated/projects/$projectId/testing'
      path: '/testing'
      fullPath: '/projects/$projectId/testing'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTestingRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/mentor/': {
      id: '/_authenticated/projects/$projectId/mentor/'
      path: '/'
      fullPath: '/projects/$projectId/mentor/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMentorIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdMentorRoute
    }
    '/_authenticated/projects/$projectId/mentor/$threadId': {
      id: '/_authenticated/projects/$projectId/mentor/$threadId'
      path: '/$threadId'
      fullPath: '/projects/$projectId/mentor/$threadId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMentorThreadIdRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdMentorRoute
    }
  }
}

interface AuthenticatedProjectsProjectIdMentorRouteChildren {
  AuthenticatedProjectsProjectIdMentorThreadIdRoute: typeof AuthenticatedProjectsProjectIdMentorThreadIdRoute
  AuthenticatedProjectsProjectIdMentorIndexRoute: typeof AuthenticatedProjectsProjectIdMentorIndexRoute
}

const AuthenticatedProjectsProjectIdMentorRouteChildren: AuthenticatedProjectsProjectIdMentorRouteChildren =
  {
    AuthenticatedProjectsProjectIdMentorThreadIdRoute:
      AuthenticatedProjectsProjectIdMentorThreadIdRoute,
    AuthenticatedProjectsProjectIdMentorIndexRoute:
      AuthenticatedProjectsProjectIdMentorIndexRoute,
  }

const AuthenticatedProjectsProjectIdMentorRouteWithChildren =
  AuthenticatedProjectsProjectIdMentorRoute._addFileChildren(
    AuthenticatedProjectsProjectIdMentorRouteChildren,
  )

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdBudgetRoute: typeof AuthenticatedProjectsProjectIdBudgetRoute
  AuthenticatedProjectsProjectIdBuildRoute: typeof AuthenticatedProjectsProjectIdBuildRoute
  AuthenticatedProjectsProjectIdDocumentsRoute: typeof AuthenticatedProjectsProjectIdDocumentsRoute
  AuthenticatedProjectsProjectIdExperimentsRoute: typeof AuthenticatedProjectsProjectIdExperimentsRoute
  AuthenticatedProjectsProjectIdMentorRoute: typeof AuthenticatedProjectsProjectIdMentorRouteWithChildren
  AuthenticatedProjectsProjectIdRequirementsRoute: typeof AuthenticatedProjectsProjectIdRequirementsRoute
  AuthenticatedProjectsProjectIdResearchRoute: typeof AuthenticatedProjectsProjectIdResearchRoute
  AuthenticatedProjectsProjectIdReviewRoute: typeof AuthenticatedProjectsProjectIdReviewRoute
  AuthenticatedProjectsProjectIdRisksRoute: typeof AuthenticatedProjectsProjectIdRisksRoute
  AuthenticatedProjectsProjectIdScheduleRoute: typeof AuthenticatedProjectsProjectIdScheduleRoute
  AuthenticatedProjectsProjectIdShowcaseRoute: typeof AuthenticatedProjectsProjectIdShowcaseRoute
  AuthenticatedProjectsProjectIdStakeholdersRoute: typeof AuthenticatedProjectsProjectIdStakeholdersRoute
  AuthenticatedProjectsProjectIdTasksRoute: typeof AuthenticatedProjectsProjectIdTasksRoute
  AuthenticatedProjectsProjectIdTestingRoute: typeof AuthenticatedProjectsProjectIdTestingRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdBudgetRoute:
      AuthenticatedProjectsProjectIdBudgetRoute,
    AuthenticatedProjectsProjectIdBuildRoute:
      AuthenticatedProjectsProjectIdBuildRoute,
    AuthenticatedProjectsProjectIdDocumentsRoute:
      AuthenticatedProjectsProjectIdDocumentsRoute,
    AuthenticatedProjectsProjectIdExperimentsRoute:
      AuthenticatedProjectsProjectIdExperimentsRoute,
    AuthenticatedProjectsProjectIdMentorRoute:
      AuthenticatedProjectsProjectIdMentorRouteWithChildren,
    AuthenticatedProjectsProjectIdRequirementsRoute:
      AuthenticatedProjectsProjectIdRequirementsRoute,
    AuthenticatedProjectsProjectIdResearchRoute:
      AuthenticatedProjectsProjectIdResearchRoute,
    AuthenticatedProjectsProjectIdReviewRoute:
      AuthenticatedProjectsProjectIdReviewRoute,
    AuthenticatedProjectsProjectIdRisksRoute:
      AuthenticatedProjectsProjectIdRisksRoute,
    AuthenticatedProjectsProjectIdScheduleRoute:
      AuthenticatedProjectsProjectIdScheduleRoute,
    AuthenticatedProjectsProjectIdShowcaseRoute:
      AuthenticatedProjectsProjectIdShowcaseRoute,
    AuthenticatedProjectsProjectIdStakeholdersRoute:
      AuthenticatedProjectsProjectIdStakeholdersRoute,
    AuthenticatedProjectsProjectIdTasksRoute:
      AuthenticatedProjectsProjectIdTasksRoute,
    AuthenticatedProjectsProjectIdTestingRoute:
      AuthenticatedProjectsProjectIdTestingRoute,
    AuthenticatedProjectsProjectIdIndexRoute:
      AuthenticatedProjectsProjectIdIndexRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCreditsRoute: typeof AuthenticatedCreditsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNewProjectRoute: typeof AuthenticatedNewProjectRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCreditsRoute: AuthenticatedCreditsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNewProjectRoute: AuthenticatedNewProjectRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
